name: Build auto-press-rs (Windows x64)
on:
  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/**"
      - "src/**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "src/**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        lua_feature:
          - lua55
          - lua54
          - lua53
          - lua52
          - lua51
          - luajit
          - luajit52
        device_info:
          - false
          - true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Rust nightly (x86_64-pc-windows-msvc)
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc
          components: rust-src
      - name: Download interception.dll
        run: |
          Invoke-WebRequest -Uri "https://github.com/bozbez/interception-sys/raw/refs/heads/master/interception-1.0.1/x64/interception.dll" `
                            -OutFile "interception.dll"
      - name: Set build features
        shell: pwsh
        id: prep-features
        run: |
          $features = "${{ matrix.lua_feature }}"
          if ("${{ matrix.device_info }}" -eq "true") {
            $features += ",device-info"
          }
          echo "features=$features" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "Building with features: $features"
      - name: Build with Cargo (Release)
        shell: pwsh
        run: |
          cargo build --release `
            --target x86_64-pc-windows-msvc `
            --features ${{ steps.prep-features.outputs.features }} `
            --no-default-features
      - name: Prepare artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "release"
          New-Item -ItemType Directory -Force -Path "release/licenses"

          Copy-Item "target/x86_64-pc-windows-msvc/release/auto-press-rs.exe" -Destination "release/auto-press-rs.exe"
          Copy-Item "interception.dll" -Destination "release/interception.dll"
          Copy-Item "LICENSE" -Destination "release/licenses/LICENSE"
          Copy-Item "licenses/interception-LGPL-3.0" -Destination "release/licenses/interception"

          if (Test-Path "demo") {
            Copy-Item -Recurse -Path "demo/" -Destination "release/" -Force -ErrorAction SilentlyContinue
          }
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: auto-press-rs-${{ matrix.lua_feature }}${{ matrix.device_info &&
            '-with-device-info' || '-no-device-info' }}
          path: release/
          if-no-files-found: warn
